### ISSUE TITLE
Ability to group entries

### ISSUE THREAD

**Issue by sadorowo** [matteo-convertino/otpmanager-nextcloud#50] opened 2024-06-10 16:03 UTC
Hello, thanks for developing this app. I'm using it because Nextcloud Passwords doesn't have support for OTP, and this isn't planned right now.

Would you mind adding a feature that will allow us to group our OTP entries? For example, tags or folders.
They could appear for example in left bar.

Example design:
![image](https://github.com/matteo-convertino/otpmanager-app/assets/97941280/6ae9162e-f9c0-47b2-a9e7-ed865d1ff902)

**Comment by matteo-convertino** [comment] 2024-07-21 18:23
Duplicate of #12

**Closed as completed by matteo-convertino** 2024-07-21 18:23 UTC

**Comment by Bytrider** [comment] 2026-07-04 06:16
Hello,

First of all, thank you very much for the continuous development of the app.

We are using the Nextcloud OTP app more and more, and it has become an important part of our daily workflow. However, as the number of entries continues to grow, it is becoming increasingly difficult to keep everything organized.

We would really appreciate further improvements, especially the ability to organize entries into groups or folders. Support for tags would also be a great addition and would make managing a large number of OTP entries much easier.

Thank you again for your great work and for continuously improving the app!
