### ISSUE TITLE
Long Name issue

### ISSUE THREAD

**Issue by tomspatz** [matteo-convertino/otpmanager-nextcloud#22] opened 2024-01-23 10:46 UTC
I try to export all my codes from the G Autheticator App on iOS. The export QR Codes works fine and are readeble by another G App. But  it is no possible to import those 4 created QR Codes into OTP Manager.
So i tried that manual and got an error by scanning singe codes with the App. "The nextcloud server returns an error. Try to reload after a while!"
But the Account is created on my iOS device but not synchronized with the Server.
So  i decided to create manualy exactly same Accounts into my NC App.
The issu is that the "Accont names" that i have created are more than 64 characters long.
So please fix it if it is possible. 

THX Tom

**Comment by matteo-convertino** [comment] 2024-01-23 10:51
Duplicate of #17.

I'm working to fix it right now.

**Comment by matteo-convertino** [comment] 2024-01-23 11:40
It should be fixed with the new [release](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.3.4). Let me know if the problem persists.

**Closed as completed by matteo-convertino** 2024-01-23 11:40 UTC
